### ISSUE TITLE
Could not find command's executable JS file. You might need to rebuild the extension.

### ISSUE THREAD

**Issue by erayack** [banteg/raycast-eips#1]
Getting this error when I tried to open extension.

**Error log:**
Reason: Could not find command's executable JS file
Domain: commands
Time: 08:32:56.253
Recovery: You might need to rebuild the extension.

<img width="743" alt="Screenshot 2024-05-10 at 11 32 55" src="https://github.com/banteg/raycast-eips/assets/37340907/765a6c20-5f52-415f-adab-560a792bc12a">

**Comment by banteg** [comment]
have built it? run `npm
run build`

i'll add this to readme

**Comment by erayack** [comment]
I've built it, but I realized there was a bug due to npm on my side. Thanks.

**Comment by ankurdubey521** [comment]
facing a similar issue, and I noticed that `npm run build` doesn't generate a `dist` folder for me. How did you solve it @erayack ?

**Comment by ankurdubey521** [comment]
nvm, I was able to fix it by manually running `npx ray build -e dist -o ./dist`
